# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import profanity_pb2 as profanity__pb2


class ProfanityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Filter = channel.unary_unary(
                '/Profanity/Filter',
                request_serializer=profanity__pb2.ProfanityRequest.SerializeToString,
                response_deserializer=profanity__pb2.ProfanityResponse.FromString,
                )


class ProfanityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Filter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfanityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Filter': grpc.unary_unary_rpc_method_handler(
                    servicer.Filter,
                    request_deserializer=profanity__pb2.ProfanityRequest.FromString,
                    response_serializer=profanity__pb2.ProfanityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Profanity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Profanity(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Filter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Profanity/Filter',
            profanity__pb2.ProfanityRequest.SerializeToString,
            profanity__pb2.ProfanityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
