# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profanity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprofanity.proto\"!\n\x10ProfanityRequest\x12\r\n\x05input\x18\x01 \x01(\t\"%\n\x11ProfanityResponse\x12\x10\n\x08\x63\x65nsored\x18\x01 \x01(\t2<\n\tProfanity\x12/\n\x06\x46ilter\x12\x11.ProfanityRequest\x1a\x12.ProfanityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profanity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PROFANITYREQUEST']._serialized_start=19
  _globals['_PROFANITYREQUEST']._serialized_end=52
  _globals['_PROFANITYRESPONSE']._serialized_start=54
  _globals['_PROFANITYRESPONSE']._serialized_end=91
  _globals['_PROFANITY']._serialized_start=93
  _globals['_PROFANITY']._serialized_end=153
# @@protoc_insertion_point(module_scope)
